// ============================================================
// themes.js — All 4 dashboard theme/skin definitions
// Each theme defines colors, fonts, mascot, name, and
// component-level style overrides.
// ============================================================

export const THEMES = {
  // ── Panel 1: Speech Playground (original warm orange) ──
  speechPlayground: {
    id: "speechPlayground",
    name: "Speech Playground",
    emoji: "🦉",
    tagline: "Warm & Playful",
    preview: { bg: "#fff5ec", accent: "#874e00", secondary: "#006b1b" },
    colors: {
      bg: "#fff5ec",
      headerBg: "rgba(255,245,236,0.85)",
      heroBg: "#91f78e",
      heroText: "#005e17",
      heroSubText: "rgba(0,94,23,0.7)",
      heroBtnBg: "#006b1b",
      heroBtnHover: "#005d16",
      snakeBg: "#ffeedc",
      snakeTrackBg: "#ffd6a2",
      snakeBarBg: "#005d16",
      snakeTextPrimary: "#874e00",
      snakeTextSub: "#765524",
      chartBg: "white",
      chartBarActive: "#006b1b",
      chartBarFilled: "#91f78e",
      chartBarEmpty: "#ffd6a2",
      badgeBg: "#4bbaff",
      badgeText: "#00344f",
      goalCardBg: "#ffeedc",
      goalBar1: "#874e00",
      goalBar2: "#00618f",
      goalTrack: "#ffd6a2",
      activityBg: "white",
      primaryText: "#432900",
      subText: "#765524",
      accent: "#874e00",
      starBg: "#ff9800",
      navActive: "#006b1b",
      navInactive: "#874e00",
      sectionHeading: "#432900",
    },
    fonts: {
      headline: "'Plus Jakarta Sans', sans-serif",
      body: "'Be Vietnam Pro', sans-serif",
    },
    mascot: "🦉",
    mascotName: "Sunny the Owl",
    snakeName: "Sunny the Sound Snake",
    heroTitle: "Ready for a word adventure?",
    heroBtn: "Start Today's Quest",
    streakIcon: "local_fire_department",
  },

  // ── Panel 6: Lingo Meadow (green/nature, Leo) ──
  lingoMeadow: {
    id: "lingoMeadow",
    name: "Lingo Meadow",
    emoji: "🌿",
    tagline: "Nature & Fresh",
    preview: { bg: "#f5f7f9", accent: "#006a35", secondary: "#00618e" },
    colors: {
      bg: "#f5f7f9",
      headerBg: "rgba(245,247,249,0.85)",
      heroBg: "linear-gradient(135deg, #006a35, #005c2d)",
      heroText: "#cdffd4",
      heroSubText: "rgba(205,255,212,0.85)",
      heroBtnBg: "white",
      heroBtnHover: "#f0fff4",
      snakeBg: "#eef1f3",
      snakeTrackBg: "#d0d5d8",
      snakeBarBg: "#006a35",
      snakeTextPrimary: "#006a35",
      snakeTextSub: "#595c5e",
      chartBg: "#eef1f3",
      chartBarActive: "#75f39c",
      chartBarFilled: "#006a35",
      chartBarEmpty: "#d0d5d8",
      badgeBg: "#fdd355",
      badgeText: "#5d4800",
      goalCardBg: "#eef1f3",
      goalBar1: "#006a35",
      goalBar2: "#00618e",
      goalTrack: "#d9dde0",
      activityBg: "white",
      primaryText: "#2c2f31",
      subText: "#595c5e",
      accent: "#006a35",
      starBg: "#fdd355",
      navActive: "#006a35",
      navInactive: "#595c5e",
      sectionHeading: "#2c2f31",
    },
    fonts: {
      headline: "'Plus Jakarta Sans', sans-serif",
      body: "'Manrope', sans-serif",
    },
    mascot: "🦊",
    mascotName: "Finn the Fox",
    snakeName: "Weekly Progress",
    heroTitle: "Great job, Leo! 🌟",
    heroBtn: "Continue Adventure",
    streakIcon: "trending_up",
    extraGoogleFont: "Manrope:wght@400;500;600;700",
  },

  // ── Panel 7: ArticPlay (clean green, Leo) ──
  articPlay: {
    id: "articPlay",
    name: "ArticPlay",
    emoji: "🎯",
    tagline: "Clean & Focused",
    preview: { bg: "#f5f7f9", accent: "#006a35", secondary: "#705900" },
    colors: {
      bg: "#f5f7f9",
      headerBg: "rgba(245,247,249,0.9)",
      heroBg: "rgba(117,243,156,0.2)",
      heroText: "#00592b",
      heroSubText: "rgba(0,89,43,0.7)",
      heroBtnBg: "linear-gradient(135deg, #006a35, #005c2d)",
      heroBtnHover: "#005c2d",
      snakeBg: "#eef1f3",
      snakeTrackBg: "#dfe3e6",
      snakeBarBg: "#006a35",
      snakeTextPrimary: "#006a35",
      snakeTextSub: "#595c5e",
      chartBg: "#eef1f3",
      chartBarActive: "#75f39c",
      chartBarFilled: "rgba(0,106,53,0.4)",
      chartBarEmpty: "rgba(0,97,142,0.4)",
      badgeBg: "#fdd355",
      badgeText: "#5d4800",
      goalCardBg: "#eef1f3",
      goalBar1: "#006a35",
      goalBar2: "#00618e",
      goalTrack: "#dfe3e6",
      activityBg: "white",
      primaryText: "#2c2f31",
      subText: "#595c5e",
      accent: "#006a35",
      starBg: "#fdd355",
      navActive: "#006a35",
      navInactive: "#00618e",
      sectionHeading: "#2c2f31",
    },
    fonts: {
      headline: "'Plus Jakarta Sans', sans-serif",
      body: "'Manrope', sans-serif",
    },
    mascot: "🎯",
    mascotName: "Coach Aria",
    snakeName: "Weekly Accuracy Trend",
    heroTitle: "The Snake's Secret 'S'",
    heroBtn: "Start Exercise",
    streakIcon: "workspace_premium",
    extraGoogleFont: "Manrope:wght@400;500;600;700",
  },

  // ── Panel 8: SpeechQuest Green (meadow, Sarah) ──
  speechQuestGreen: {
    id: "speechQuestGreen",
    name: "SpeechQuest",
    emoji: "🐍",
    tagline: "Meadow & Bright",
    preview: { bg: "#f5f7f9", accent: "#006a35", secondary: "#705900" },
    colors: {
      bg: "#f5f7f9",
      headerBg: "rgba(245,247,249,0.9)",
      heroBg: "linear-gradient(180deg, #e0f2f1 0%, #f5f7f9 100%)",
      heroText: "#00592b",
      heroSubText: "#595c5e",
      heroBtnBg: "linear-gradient(135deg, #006a35, #75f39c)",
      heroBtnHover: "#005c2d",
      snakeBg: "#eef1f3",
      snakeTrackBg: "#e5e9eb",
      snakeBarBg: "#006a35",
      snakeTextPrimary: "#006a35",
      snakeTextSub: "#595c5e",
      chartBg: "white",
      chartBarActive: "#006a35",
      chartBarFilled: "rgba(0,106,53,0.4)",
      chartBarEmpty: "#e5e9eb",
      badgeBg: "#fdd355",
      badgeText: "#5d4800",
      goalCardBg: "#eef1f3",
      goalBar1: "#006a35",
      goalBar2: "#00618e",
      goalTrack: "#e5e9eb",
      activityBg: "white",
      primaryText: "#2c2f31",
      subText: "#595c5e",
      accent: "#006a35",
      starBg: "#006a35",
      navActive: "#006a35",
      navInactive: "#595c5e",
      sectionHeading: "#2c2f31",
    },
    fonts: {
      headline: "'Plus Jakarta Sans', sans-serif",
      body: "'Manrope', sans-serif",
    },
    mascot: "🐍",
    mascotName: "Sammy the Snake",
    snakeName: "Accuracy Trend",
    heroTitle: "Welcome, Sarah!",
    heroBtn: "Start Exercise",
    streakIcon: "auto_awesome",
    extraGoogleFont: "Manrope:wght@400;500;600;700",
  },
};

export const THEME_ORDER = ["speechPlayground", "lingoMeadow", "articPlay", "speechQuestGreen"];
export const DEFAULT_THEME = "speechPlayground";
